# Generated by Django 4.2.7 on 2023-11-03 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_Messages_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_ID', models.CharField(max_length=32)),
                ('sender_name', models.CharField(max_length=32)),
                ('sender_image', models.URLField(blank=True)),
                ('sender_chat_message', models.TextField(blank=True, null=True)),
                ('message_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chat_Room_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_ID', models.CharField(blank=True, max_length=10, null=True)),
                ('admin_name', models.CharField(blank=True, max_length=64, null=True)),
                ('chat_room_name', models.CharField(max_length=128)),
                ('chatroom_messages', models.ManyToManyField(blank=True, related_name='chat_model_room', to='CHAT_app.chat_messages_model')),
            ],
        ),
        migrations.AddField(
            model_name='chat_messages_model',
            name='chat_room_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CHAT_app.chat_room_model'),
        ),
    ]
