# Generated by Django 4.2.7 on 2023-11-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHAT_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_room_model',
            name='admin_ID',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='chat_room_model',
            name='admin_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
