# Generated by Django 4.1.3 on 2023-11-03 04:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CHAT_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_messages_model',
            name='message_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
